### ISSUE TITLE
What is the deployed python API URL?

### ISSUE THREAD

**Issue by GGWPXXXX** [MQ-xz/QuickSearchAdvanced#2]
What is the deployed python API URL?

**Comment by MQ-xz** [comment]
To answer the questions we used a python program to search the questions and grab answers from google. and it is connected to the extension.

check [API/app.py](https://github.com/MQ-xz/QuickSearchAdvanced/blob/master/API/app.py) it's a python script in [flask](https://flask.palletsprojects.com/en/2.0.x/) you can run it on the local machine or a server. then replace the `YOUR_API_URL` on file [content.js](https://github.com/MQ-xz/QuickSearchAdvanced/blob/master/Extension/content.js) with the URL on the python script API.

**Comment by quangvm2310123** [comment]
Can you have get example about your api url is not, at my api url of your write I am is "AppName": "Quick Search Advanced",
   "Version": "1.0.2"
