### ISSUE TITLE
Help me with this

### ISSUE THREAD

**Issue by quangvm2310123** [MQ-xz/QuickSearchAdvanced#3]
Can you have get example about your api url is not, at my api url of your write I am is "AppName": "Quick Search Advanced",
"Version": "1.0.2"

**Comment by MQ-xz** [comment]
ya, it's correct, means the API is running perfectly. now you can replace the `YOUR_API_URL` in [content.js](https://github.com/MQ-xz/QuickSearchAdvanced/blob/master/Extension/content.js)  with the URL of API.

for example, the API URL  maybe looks like `http://127.0.0.1:5000`  after replacing `YOUR_API_URL` on [content.js](https://github.com/MQ-xz/QuickSearchAdvanced/blob/master/Extension/content.js) with URL its like `https://127.0.0.1:5000/?question=`
